### PR TITLE
Update tests in python-publish workflow

### PR DESCRIPTION
**Pull request by han16nah**

### CODE REVIEW

**Comment by lwiniwar** [comment]
Hmm I thought the idea of this test was whether a remote server (i.e., not 127.0.0.1) can be used to run `pytreedb`. Or are we considering this covered sufficiently in the other CI pipeline?

You will also want to point the CI to the 'normal' PyPI instead of testing.pypi.org at some point.

**Comment by han16nah** [comment]
> Hmm I thought the idea of this test was whether a remote server (i.e., not 127.0.0.1) can be used to run `pytreedb`. Or are we considering this covered sufficiently in the other CI pipeline?
> 
> You will also want to point the CI to the 'normal' PyPI instead of testing.pypi.org at some point.

@lwiniwar Shall we replace the test by one of the other server tests which we have in the [python-app.yml](https://github.com/3dgeo-heidelberg/pytreedb/blob/main/.github/workflows/python-app.yml), e.g. https://github.com/3dgeo-heidelberg/pytreedb/blob/06b56c6732da1627f26cc75e0ac77da2bfc600f3/.github/workflows/python-app.yml#L78

And sure, once you approve, we can exchange the link for publishing in the "normal" PyPi

**Comment by lwiniwar** [comment]
I would say either (a) do all the tests that are also in the other CI or (b) do no tests in this script, and rely on the user not to push untested versions (or versions where the tests fail) to PyPI.
Can we 'include' the other file in here? Something like explained here maybe... https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow

**Comment by bhoefle-3dgeo** [comment]
> I would say either (a) do all the tests that are also in the other CI or (b) do no tests in this script, and rely on the user not to push untested versions (or versions where the tests fail) to PyPI. Can we 'include' the other file in here? Something like explained here maybe... https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow

I agree. For me - at the current stage - it makes no sense to run different tests for CI than for publishing. Including the existing tests would be a good option because it then only needs one place to maintain. If this is not possible and a redundant test implementation would be required, I opt for skipping it because CI should guarantee consistency anyway.

**Comment by han16nah** [comment]
obsolete

**Pull request closed without merging**
