### PR TITLE
Contributing

### PR DESCRIPTION
**Pull request by han16nah**
Add [CONTRIBUTING.md](https://github.com/3dgeo-heidelberg/pytreedb/blob/contributing/CONTRIBUTING.md)
created from [this template](https://github.com/allenai/python-package-template/blob/main/CONTRIBUTING.md)

solves #48 

Once we are happy and merge this PR, we should also link to CONTRIBUTING.md in the README

### CODE REVIEW

**Comment by lwiniwar** [comment]
I would suggest to reduce complexity in the *PR* part by using the github web interface:

1) Fork the repository using the web interface
2) Clone and edit locally or edit online
3) Create a PR using the web interface:
grafik
4) Ensure it is up to date using the PR interface ("fetch updates")

For me, this is much more straightforward than adding a remote source in the repo, especially if I only want to contribute once (e.g. fixing a typo, ...)

**Comment by lwiniwar** [comment]
I would also add the commands to run `pytest` and make sure that contributers understand that we repeat these tests upon PR submission (by means of github actions), and are only able/willing to merge if they pass

**Comment by han16nah** [comment]
> I would also add the commands to run `pytest` and make sure that contributers understand that we repeat these tests upon PR submission (by means of github actions), and are only able/willing to merge if they pass

Yes, good suggestion, we can even explain the usage of the markers, e.g. to only run tests related to importing data etc. :)

**Comment by han16nah** [comment]
> I would suggest to reduce complexity in the _PR_ part by using the github web interface:
> 
>     1. Fork the repository using the web interface
> 
>     2. Clone and edit locally or edit online
> 
>     3. Create a PR using the web interface:
>        grafik
> 
>     4. Ensure it is up to date using the PR interface ("fetch updates")
> 
> 
> For me, this is much more straightforward than adding a remote source in the repo, especially if I only want to contribute once (e.g. fixing a typo, ...)

Okay sure, I agree! :)

**Review by lwiniwar — APPROVED** [review]
perfect, thanks!

**Pull request merged**
